config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :lists do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
  validates :comment, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # def index
  #   @bookmarks = Bookmark.all
  # end

  def show
    @bookmark = Bookmark.find_by(id: params[:id])
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  # def edit
  #   @bookmark = Bookmark.find_by(id: params[:id])
  # end

  # def update
  #   bookmark = Bookmark.find_by(id: params[:id])
  #   bookmark.update(bookmark_params)
  #   redirect_to bookmark_path(bookmark)
  # end

  def destroy
    bookmark = Bookmark.find(params[:id])
    bookmark.destroy
    redirect_to list_path(bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find_by(id: params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    redirect_to list_path(@list)
  end

  def edit
    @list = List.find_by(id: params[:id])
  end

  def update
    list = List.find_by(id: params[:id])
    list.update(list_params)
    redirect_to list_path(list)
  end

  def destroy
    list = List.find_by(id: params[:id])
    list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>
<%= link_to 'New Bookmark', new_bookmark_path %>
<div> style="padding: 10px">
  <% @bookmarks.each do |bookmark| %>
    <p style="border: 1px solid black; padding: 5px; background-color: #eee; border-radius: 5px;">
    <%= bookmark.comment %>
    <%= link_to "View bookmark", bookmark_path(bookmark) %>
    </p>
  <% end %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark:</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Create bookmark" %>
<% end %>
<%= link_to "Cancel", list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div style="margin:10px">
  <h1>Lists view</h1>
</div>
<div style="margin:10px">
  <a href="<%= new_list_path %>" style="display: inline-block; padding: 10px 20px; margin-top: 10px; background-color: #4caf50; color: white; text-decoration: none; border-radius: 4px; font-size: 16px; border: none; cursor: pointer; transition: background-color 0.3s ease;">New List</a>
</div>
<div style="padding: 10px">
  <% @lists.each do |list| %>
    <p style="border: 1px solid black; padding: 5px; background-color: #eee; border-radius: 5px; width: 25%; justify-content: centre; display: flex; margin: 10px 0;">
    <%= link_to list.name, list_path(list) %>
    </p>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>New List:</h1>
<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Create list" %>
<% end %>

<a href="<%= lists_path %>" style="display: inline-block; padding: 10px 20px; margin-top: 10px; background-color: #4caf50; color: white; text-decoration: none; border-radius: 4px; font-size: 16px; border: none; cursor: pointer; transition: background-color 0.3s ease;">Cancel</a>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<div style="display: flex; flex-wrap: wrap; gap: 20px;">
  <% if @list.movies.length > 0 %>
    <% @list.bookmarks.each do |bookmark| %>
      <% movie = bookmark.movie %>
      <div style="background-color: #f2f2f2; padding: 10px; border-radius: 4px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); width: 200px; position: relative;">
        <h3 style="margin: 0; font-size: 18px; color: #333;"><%= bookmark.movie.title %></h3>
        <p style="margin: 8px 0; font-size: 14px; color: #666;"><%= bookmark.movie.overview %></p>
        <div style="position: absolute; bottom: 10px; left: 50%; transform: translateX(-50%);">
          <%= button_to list_bookmark_path(@list, bookmark), method: :delete, data: { confirm: 'Are you sure?' }, style: "color: dark-blue; border: 1px; padding: 10px 20px; font-size: 24px; border-radius: 50%; cursor: pointer; transition: background-color 0.3s ease;" do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
      <%= image_tag movie.poster_url, alt: "Movie poster", width: 200 %>
    <% end %>
  <% else %>
    <p>This list is empty.</p>
  <% end %>
</div>
<a href="<%= new_list_bookmark_path(@list) %>" style="display: inline-block; padding: 10px 20px; margin-top: 10px; background-color: #4caf50; color: white; text-decoration: none; border-radius: 4px; font-size: 16px; border: none; cursor: pointer; transition: background-color 0.3s ease;">Add a new movie</a><br>
<a href="<%= lists_path %>" style="display: inline-block; padding: 10px 20px; margin-top: 10px; background-color: #4caf50; color: white; text-decoration: none; border-radius: 4px; font-size: 16px; border: none; cursor: pointer; transition: background-color 0.3s ease;">See all lists</a>